### ISSUE TITLE
lealone-mysql-plugin插件，在每次重启lealone服务以后，就需要再次手动启动mysql插件，能否做成lealone服务重启，自动启动插件

### ISSUE THREAD

**Issue by tangzhongshan** [lealone/Lealone#228]
还有lealone-mysql-plugin插件，在每次重启lealone服务以后，就需要再次手动启动mysql插件，这个可以做成在lealone服务启动以后，自动启动mysql插件

**Comment by codefollower** [comment]
> 还有lealone-mysql-plugin插件，在每次重启lealone服务以后，就需要再次手动启动mysql插件，这个可以做成在lealone服务启动以后，自动启动mysql插件

create、start plugin 命令是用于动态管理插件，
想要自动启动 mysql 插件，有个更简单的办法，不需要执行 create、start plugin 命令的。
先把 lealone-mysql-plugin-6.0.0.jar 扔到 lealone 安装目录的 lib 子目录中，
然后像下面这样配置一下 conf/lealone.yaml
```yaml
sql_engines:
  - name: Lealone
    enabled: true
    parameters: {
        # key1: v1,
        # key2: v2,
    }
  - name: MySQL
    enabled: true
    parameters: {
        # key1: v1,
        # key2: v2,
    }

protocol_server_engines:
  - name: TCP
    enabled: true
    parameters: {
        port: 9210,
        allow_others: true,
        ssl: false
    }
  - name: MySQL
    enabled: true
    parameters: {
        port: 3306,
        allow_others: true,
        ssl: false
    }
```
